# Generated by Django 3.0.8 on 2020-07-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(blank=True, max_length=256, null=True)),
                ('match_status', models.CharField(blank=True, max_length=256, null=True)),
                ('match_date', models.CharField(blank=True, max_length=256, null=True)),
                ('match_time', models.CharField(blank=True, max_length=256, null=True)),
                ('match_hometeam_name', models.CharField(blank=True, max_length=256, null=True)),
                ('match_hometeam_score', models.CharField(blank=True, max_length=256, null=True)),
                ('match_awayteam_name', models.CharField(blank=True, max_length=256, null=True)),
                ('match_awayteam_score', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_key', models.CharField(blank=True, max_length=256, null=True)),
                ('player_name', models.CharField(blank=True, max_length=256, null=True)),
                ('player_number', models.CharField(blank=True, max_length=256, null=True)),
                ('player_country', models.CharField(blank=True, max_length=256, null=True)),
                ('player_age', models.CharField(blank=True, max_length=256, null=True)),
                ('player_match_played', models.CharField(blank=True, max_length=256, null=True)),
                ('player_goals', models.CharField(blank=True, max_length=256, null=True)),
                ('player_yellow_cards', models.CharField(blank=True, max_length=256, null=True)),
                ('player_red_cards', models.CharField(blank=True, max_length=256, null=True)),
                ('team_name', models.CharField(blank=True, max_length=256, null=True)),
                ('team_key', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
